import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navLinks = [
    { name: "Overview", url: "/" },
    { name: "Africa", url: "/afr" },
    { name: "Americas", url: "/ame" },
    { name: "Asia", url: "/asi" },
    { name: "Europe", url: "/eur" },
    { name: "Oceania", url: "/oce" },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="p-4">
          <ul className="flex gap-4">
            {navLinks.map((nav) => (
              <li key={nav.url} className="list-none">
                <Link href={nav.url} className="underline">{nav.name}</Link>
              </li>
            ))}
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}
